### ISSUE TITLE
编写「如何给 19wu 贡献代码」指南

### ISSUE THREAD

**Issue by saberma** [19wu/19wu#41]
可能有些参与者不知道怎么做。

谁能写一下实例指南，最好有图有真相，从以下几个步骤来讲：
- 如何 fork 19wu 的源代码
- 在 issue 中留名，表示你正在做
- 开始修改代码
- git commit 时注意要加上 issue 的 id 号，让两者关联
- 如何提交 Pull Request

**Comment by JellyBool** [comment]
真心感谢 @nightire @saberma 今天仔细看了，也很庆幸有了自己的第一个PR。多说两句就是，很敬佩 @nightire 这位，不管是在github，还是SF，在你身上学到的东西太多了，不管是编程的相关知识还是对待编程的态度，非常感谢

**Comment by nightire** [comment]
@JellyBool 谢谢你的肯定，这么晚还没睡啊，这么老的 Issue 也被你翻出来了呀……原来我 2012 年就知道善用 rebase 了，忽然佩服了一下自己 :smile:

早点睡，晚安！

**Comment by JellyBool** [comment]
哈哈哈，发完就睡了。希望某一天，也能成为像你那样的人。yoshi  @nightire
