### ISSUE TITLE
rake setup报错

### ISSUE THREAD

**Issue by angelfan** [19wu/19wu#641]
LoadError: cannot load such file -- guard/guard

**Comment by windy** [comment]
试下 bundle exec rake setup 是否有问题?

**Comment by angelfan** [comment]
找到问题的原因了
因为带着源码中的gemfile.lock执行bundle instal 有些gem因为网络的原因无法安装
所以我我把gemfile.lock文件删除了 重新生成的genfile.lock文件中关于guard那一部分可能是导致的，
目前在用老版本的gemfile.lock 执行bundle install

**Comment by Kevinqingyu** [comment]
同样的问题，原带的gemfile.lock 文件里面的gem版本过低，导致bundle install 的时候 几乎是过不去的。相关依赖不知如何更改 

**Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /Users/a1/.rvm/rubies/ruby-2.2.3/bin/ruby -r ./siteconf20170215-2459-1j7hix2.rb extconf.rb
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling generator.c
In file included from generator.c:1:
./../fbuffer/fbuffer.h:175:47: error: too few arguments provided to function-like macro invocation
    VALUE result = rb_str_new(FBUFFER_PAIR(fb));
                                              ^
/Users/a1/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0/ruby/intern.h:793:9: note: macro 'rb_str_new' defined here
#define rb_str_new(str, len) __extension__ (    \
        ^
In file included from generator.c:1:
./../fbuffer/fbuffer.h:175:11: warning: incompatible pointer to integer conversion initializing 'VALUE' (aka 'unsigned long') with an expression of type 'VALUE
(const char *, long)' (aka 'unsigned long (const char *, long)') [-Wint-conversion]
    VALUE result = rb_str_new(FBUFFER_PAIR(fb));
          ^        ~~~~~~~~~~
1 warning and 1 error generated.
make: *** [generator.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/a1/.rvm/gems/ruby-2.2.3/gems/json-1.8.0 for inspection.
Results logged to /Users/a1/.rvm/gems/ruby-2.2.3/extensions/x86_64-darwin-14/2.2.0-static/json-1.8.0/gem_make.out

An error occurred while installing json (1.8.0), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.0'` succeeds before bundling.**
